### ISSUE TITLE
Change repo name

### ISSUE THREAD

**Issue by luarx** [safe-global/safe-react-status#9]
What about renaming the repo?
Idea:
- `safe-transaction-services-status`

Reasons:
- Having the "react" name in the title is not helpful
- Changing that we will be inline with other repos as https://github.com/safe-global/safe-services-status

**Comment by dasanra** [comment]
@luarx what do you think about `safe-transaction-services-status-page`? I was checking and there could be some confusion between

`safe-transaction-service`
`safe-config-service`
`safe-services-status`

Even if it evolves to a general status page could be `safe-services-status-page`

**Comment by luarx** [comment]
Sounds good to me also 🤝 

Wdyt @Uxio0 ? (as it is related with safe-transaction-service statuses)

**Comment by Uxio0** [comment]
I would only go with `safe-services-status-page` if you are planning to check more services (also remember that config service is part of Walet and no Core).

Currently this page only shows indexing status (not even liveness), so I would go with `safe-transaction-service-status-page`

**Comment by dasanra** [comment]
Agree with that. I'll rename then to `safe-transaction-service-status-page`
